services:
  redis:
      image: redis:7.0.11-alpine

  django:
    container_name: django
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/app
    ports:
      - 8001:8000
    environment:
      - DEBUG=1
      - SECRET_KEY=87sdfga8sdfasdfa8sdf8988sadf
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis

  celery:
    container_name: celery
    build:
      context: .
    command: celery --app=core worker -l INFO -Q queue1  # Assuming 'core' is where celery.py is located
    volumes:
      - .:/usr/src/app
    environment:
      - DEBUG=1
      - SECRET_KEY=87sdfga8sdfasdfa8sdf8988sadf
      - ALLOWED_HOSTS=localhost,127.0.0.1
    depends_on:
      - redis
      - django

  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0
    volumes:
      - esdata01:/usr/share/elasticsearch/data  # Corrected line
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
volumes:
  esdata01:
